pull_request_rules:
  - name: Automatic merge design doc changes on approval
    conditions:
      - -files~=^(!?docs/design-doc/)
      - "#approved-reviews-by>=1"
      - status-success=WIP
      - status-success=Semantic Pull Request
    actions:
      merge:
        method: merge

  - name: Automatic approve design doc changes for tianhaoz95
    conditions:
      - author=tianhaoz95
      - -files~=^(!?docs/design-doc/)
    actions:
      review:
        type: APPROVE
        message: Hi tianhaoz95! Since you are the owner of the repository, your changes in design docs is automatically approved!
