pull_request_rules:
  - name: Automatic merge design doc changes on approval
    conditions:
      - -files~=^(!?docs/design-doc/)
      - "#approved-reviews-by>=1"
      - status-success=WIP
      - status-success=Semantic Pull Request
    actions:
      merge:
        method: merge
