name: App Integration Tests Android

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - 'app/*'
  schedule:
    - cron: '* */6 * * *'

jobs:
  android-integration-test:
    name: run integration tests on Android
    defaults:
      run:
        working-directory: app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.20.2"
          channel: "stable"
      - name: configure Flutter
        run: |
          flutter channel master
          flutter config --enable-web --enable-macos-desktop --enable-linux-desktop
          flutter upgrade
          flutter --version
      - name: run basic tests
        run: |
          flutter pub get
          flutter analyze
          flutter test
      - name: run integration tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2.6.0
        with:
          api-level: 28
          profile: "pixel_xl"
          script: |
            /Users/runner/Library/Android/sdk/tools/bin/avdmanager list
            sleep 20
            flutter doctor -v
            cd ./app && flutter drive --target=test_driver/app.dart