name: App Integration Tests iPad

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - 'app/*'
  schedule:
    - cron: '* */6 * * *'

jobs:
  ipad-integration-test:
    name: run integration test on iPad
    defaults:
      run:
        working-directory: app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.20.2"
          channel: "stable"
      - name: upgrade Flutter
        run: |
          flutter channel master
          flutter config --enable-web --enable-macos-desktop --enable-linux-desktop
          flutter upgrade
          flutter --version
      - name: run quick Tests
        run: |
          flutter analyze
          flutter test
      - name: list simulators
        run: xcrun instruments -s
      - name: start simulator
        env:
          IPAD_MODEL: 'iPad Pro (12.9-inch) (4th generation) (13.6)'
        run: |
          UDID=$(
            xcrun instruments -s |
            awk \
              -F ' *[][]' \
              -v 'device=${IPAD_MODEL}' \
              '$1 == device { print $2 }'
          )
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - name: install server dependencies
        run: flutter pub get
      - name: run offline device end to end test
        run: flutter drive --target=test_driver/mock.dart
