name: App Build Tests

on:
  push:
    branches:
      - 'master'
    paths:
      - 'app/*'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'app/*'
  schedule:
    - cron: '* */6 * * *'

jobs:
  build-test:
    name: run build tests
    defaults:
      run:
        working-directory: app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.20.2"
          channel: "stable"
      - name: configure Flutter
        run: |
          flutter channel master
          flutter config --enable-web --enable-macos-desktop --enable-linux-desktop
          flutter upgrade
          flutter --version
          flutter devices
      - name: build iOS
        run: flutter build ios --release --no-codesign
      - name: build Android apk
        run: flutter build apk --split-per-abi
      - name: build Android appbundle
        run: flutter build appbundle
      - name: build Web
        run: flutter build web
      - name: build MacOS
        run: flutter build macos
      - name: build Linux
        run: flutter build linux